#必须要加一个空格
#开发环境
server:
  port: 8080
girl:
  cupSize: B
  age: 18

spring:
 datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgirl
    username: spring
    password: aa111111

 jpa:
    hibernate:
      ddl-auto: update  #不删除原来的表。只是新建没有的表
#      ddl-auto: create  #自动创建表,创建一个空的表，在这之前的表被删掉。
    show-sql: true  #可以让我们在控制台看见sql语句
    database-platform:  org.hibernate.dialect.MySQL5InnoDBDialect #创建表的时候使用InnoDB引擎，不然默认是MyISAM

 redis:
   port: 6379
   url:
   lettuce:
     pool:
       # 池在给定时间可以分配的最大连接数。使用负值无限制。
       max-active: 8
       # 池中“空闲”连接的最大数量。使用负值表示无限数量的空闲连接。
       max-idle: 8
       # 连接分配在池被耗尽时抛出异常之前应该阻塞的最长时间量（以毫秒为单位）。使用负值可以无限期地阻止。
       max-wait: -1
       # 目标为保持在池中的最小空闲连接数。这个设置只有在正面的情况下才有效果。
       min-idle: 0
     # 以毫秒为单位的连接超时。
     shutdown-timeout: 0
   host: localhost
   #使用哪个数据库，默认有16个。
   database: 0

